name: usbutils # you probably want to 'snapcraft register <name>'
version: '008' # just for humans, typically '1.2+git' or '1.3.2'
summary: snap to run lsusb # 79 char long summary
description: |
  snap to run lsusb using usbutils version 008.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    lsusb:
        command: usr/bin/lsusb
        plugs: [hardware-observe]

parts:
    usbutils:
        plugin: make
        source: https://www.kernel.org/pub/linux/utils/usb/usbutils/usbutils-008.tar.gz
        build-packages: 
            - libusb-1.0-0-dev
            - libusb-1.0-0
        stage-packages:
            - libusb-1.0-0-dev
            - libusb-1.0-0
        prepare: |
            ./configure

